extends Node

signal work_selected(worker)
signal other_selected(node)
signal task_activated(task)
signal task_completed(task)
signal task_work_started(task_instance)
signal task_work_stopped(task_instance)
signal day_changed(new_day)
signal task_is_overdue(task)
signal worker_charging()
signal worker_stopped_charging()
signal worker_sleeping()
signal worker_stopped_sleeping()
signal hour_changed(hour: int)
